// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Subscribes.Persistence.Contexts;

namespace Subscribes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191028160209_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Subscribes.Domain.Models.Subscribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataEnd");

                    b.Property<DateTime>("DataStart");

                    b.Property<int>("ExtProdId");

                    b.Property<int>("ExtUserId");

                    b.HasKey("Id");

                    b.ToTable("Subscribes-Info","subscribes");
                });
#pragma warning restore 612, 618
        }
    }
}
